### ISSUE TITLE
Does not seem to work well with embeds?

### ISSUE THREAD

**Issue by reinaka42** [HandaArchitect/obsidian-banner-snippet#11] opened 2024-08-11 05:57 UTC
Hi, I encountered a problem when trying to embed a note into another note (both have banners). The banner ended up appearing in the embedded note.

So I tried to circumvent this by adding a header and only embedding a section of that note into the other one. But then the embed ended up with a large margin at the top in reading mode.

I wonder if there is any solution to this yet? Thanks a lot.

**Comment by HandaArchitect** [comment] 2024-08-11 06:51
I do remember removing a CSS selector to only select the first instance of the banner image.

I have a new version yet to be released. I'll start adding the selector back in to sort that out.

Thank you for letting me know!

**Comment by HandaArchitect** [comment] 2024-08-11 08:33
@reinaka42 sorry, just realised what you were saying. In an embedded note with a banner, it is expected that the banner will also show on preview. However, I did notice too that there can be a margin that prevents the preview from functioning as intended when a note is embedded. I am happy to say that I have found a fix for this. I'll be releasing a new version soon.

**Comment by HandaArchitect** [comment] 2024-08-12 08:37
Resolve on [v1.3.1](https://github.com/HandaArchitect/obsidian-banner-snippet/releases/tag/v1.3.1)

**Closed as completed by HandaArchitect** 2024-08-12 08:37 UTC
